// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiQQcYwdA1Cq3aljRFHaG3qceoJ411UsE',
    appId: '1:958799076376:web:6dd08fc12c3e23060e376d',
    messagingSenderId: '958799076376',
    projectId: 'giku-e3900',
    authDomain: 'giku-e3900.firebaseapp.com',
    storageBucket: 'giku-e3900.appspot.com',
    measurementId: 'G-LN2VD7EZDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBALXbyFJT-kvA8hzStUCcd9qifq6rqZEI',
    appId: '1:958799076376:android:155dfae99d82a4ac0e376d',
    messagingSenderId: '958799076376',
    projectId: 'giku-e3900',
    storageBucket: 'giku-e3900.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Q4kJp19y3K3daZ1ct6XQbtsR5K9P6TY',
    appId: '1:958799076376:ios:8198ea6eaf1c398c0e376d',
    messagingSenderId: '958799076376',
    projectId: 'giku-e3900',
    storageBucket: 'giku-e3900.appspot.com',
    iosBundleId: 'com.example.giku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Q4kJp19y3K3daZ1ct6XQbtsR5K9P6TY',
    appId: '1:958799076376:ios:64318599287dc8470e376d',
    messagingSenderId: '958799076376',
    projectId: 'giku-e3900',
    storageBucket: 'giku-e3900.appspot.com',
    iosBundleId: 'com.example.giku.RunnerTests',
  );
}
